### ISSUE TITLE
Error from sync_datasets

### ISSUE THREAD

**Issue by ghan1t** [ghan1t/udev-trigger-zfs-autobackup#2]
If I backup large amount of data - arround 3 TB, one dataset with 10 subdatasets - with your script, zfs-autobackup will fail after sending/receiving three out of ten datasets. It works with standalone zfs-autobackup command.

https://www.truenas.com/community/threads/udev-trigger-zfs-autobackup-to-removable-disk-offsite-backup.100570/post-803248

2024-01-14 01:51:59 - UDEV-Trigger - INFO - Starting ZFS-Autobackup for pool backuppool with parameters:
zfs-autobackup-v -d --strip-path=1 --allow-empty --clear-mountpoint --keep-source=10,1d1w,1w1m,1m1y --keep-target=10,1d1w,1w1m,1m1y backuppool backuppool
2024-01-14 01:52:43 - UDEV-Trigger - ERROR - An unexpected error occurred. Backup mail have failed. Please investigate.

Error:
[Errno 5] Input/output error
Traceback (most recent call last):
  File "/mnt/ssdpool/scriptroot/scripts/autobackup/venv/lib/python3.11/site-packages/zfs_autobackup/ZfsAutobackup.py", line 362, in sync_datasets
    source_dataset.sync_snapshots(target_dataset, show_progress=self.args.progress,
  File "/mnt/ssdpool/scriptroot/scripts/autobackup/venv/lib/python3.11/site-packages/zfs_autobackup/ZfsDataset.py", line 1181, in sync_snapshots
    source_snapshot.transfer_snapshot(target_snapshot, features=features,
  File "/mnt/ssdpool/scriptroot/scripts/autobackup/venv/lib/python3.11/site-packages/zfs_autobackup/ZfsDataset.py", line 785, in transfer_snapshot
    target_snapshot.recv_pipe(pipe, features=features, filter_properties=filter_properties,
  File "/mnt/ssdpool/scriptroot/scripts/autobackup/venv/lib/python3.11/site-packages/zfs_autobackup/ZfsDataset.py", line 699, in recv_pipe
    self.zfs_node.run(cmd, inp=pipe, valid_exitcodes=valid_exitcodes)
  File "/mnt/ssdpool/scriptroot/scripts/autobackup/venv/lib/python3.11/site-packages/zfs_autobackup/ExecuteNode.py", line 176, in run
    if not cmd_pipe.execute():
           ^^^^^^^^^^^^^^^^^^
  File "/mnt/ssdpool/scriptroot/scripts/autobackup/venv/lib/python3.11/site-packages/zfs_autobackup/CmdPipe.py", line 118, in execute
    self.__process_outputs(selectors)
  File "/mnt/ssdpool/scriptroot/scripts/autobackup/venv/lib/python3.11/site-packages/zfs_autobackup/CmdPipe.py", line 158, in __process_outputs
    item.stderr_handler(line)
  File "/mnt/ssdpool/scriptroot/scripts/autobackup/venv/lib/python3.11/site-packages/zfs_autobackup/ExecuteNode.py", line 131, in stderr_handler
    self._parse_stderr(line, hide_errors)
  File "/mnt/ssdpool/scriptroot/scripts/autobackup/venv/lib/python3.11/site-packages/zfs_autobackup/ZfsNode.py", line 171, in _parse_stderr
    self.parse_zfs_progress(line, hide_errors, "STDERR > ")
  File "/mnt/ssdpool/scriptroot/scripts/autobackup/venv/lib/python3.11/site-packages/zfs_autobackup/ZfsNode.py", line 155, in parse_zfs_progress
    self.logger.progress(
  File "/mnt/ssdpool/scriptroot/scripts/autobackup/venv/lib/python3.11/site-packages/zfs_autobackup/CliBase.py", line 104, in progress
    self.log.progress(txt)
  File "/mnt/ssdpool/scriptroot/scripts/autobackup/venv/lib/python3.11/site-packages/zfs_autobackup/LogConsole.py", line 66, in progress
    print(">>> {}\r".format(txt), end='', file=sys.stderr)
OSError: [Errno 5] Input/output error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/ssdpool/scriptroot/scripts/autobackup/venv/lib/python3.11/site-packages/zfs_autobackup/ZfsAutobackup.py", line 501, in run
    fail_count = self.sync_datasets(
                 ^^^^^^^^^^^^^^^^^^^
  File "/mnt/ssdpool/scriptroot/scripts/autobackup/venv/lib/python3.11/site-packages/zfs_autobackup/ZfsAutobackup.py", line 376, in sync_datasets
    source_dataset.error("FAILED: " + str(e))
  File "/mnt/ssdpool/scriptroot/scripts/autobackup/venv/lib/python3.11/site-packages/zfs_autobackup/ZfsDataset.py", line 59, in error
    self.zfs_node.error("{}: {}".format(self.name, txt))
  File "/mnt/ssdpool/scriptroot/scripts/autobackup/venv/lib/python3.11/site-packages/zfs_autobackup/ZfsNode.py", line 177, in error
    self.logger.error("{} {}".format(self.description, txt))
  File "/mnt/ssdpool/scriptroot/scripts/autobackup/venv/lib/python3.11/site-packages/zfs_autobackup/CliBase.py", line 98, in error
    self.log.error(txt)
  File "/mnt/ssdpool/scriptroot/scripts/autobackup/venv/lib/python3.11/site-packages/zfs_autobackup/LogConsole.py", line 33, in error
    print("! " + txt, file=sys.stderr)
OSError: [Errno 5] Input/output error
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/ssdpool/scriptroot/scripts/autobackup/venv/lib/python3.11/site-packages/zfs_autobackup/ZfsAutobackup.py", line 501, in run
    fail_count = self.sync_datasets(
                 ^^^^^^^^^^^^^^^^^^^
  File "/mnt/ssdpool/scriptroot/scripts/autobackup/venv/lib/python3.11/site-packages/zfs_autobackup/ZfsAutobackup.py", line 376, in sync_datasets
    source_dataset.error("FAILED: " + str(e))
  File "/mnt/ssdpool/scriptroot/scripts/autobackup/venv/lib/python3.11/site-packages/zfs_autobackup/ZfsDataset.py", line 59, in error
    self.zfs_node.error("{}: {}".format(self.name, txt))
  File "/mnt/ssdpool/scriptroot/scripts/autobackup/venv/lib/python3.11/site-packages/zfs_autobackup/ZfsNode.py", line 177, in error
    self.logger.error("{} {}".format(self.description, txt))
  File "/mnt/ssdpool/scriptroot/scripts/autobackup/venv/lib/python3.11/site-packages/zfs_autobackup/CliBase.py", line 98, in error
    self.log.error(txt)
  File "/mnt/ssdpool/scriptroot/scripts/autobackup/venv/lib/python3.11/site-packages/zfs_autobackup/LogConsole.py", line 33, in error
    print("! " + txt, file=sys.stderr)
OSError: [Errno 5] Input/output error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/ssdpool/scriptroot/scripts/autobackup/backup.py", line 39, in backup
    captured_output = run_zfs_autobackup(pool_config.autobackup_parameters, logger)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/ssdpool/scriptroot/scripts/autobackup/backup.py", line 89, in run_zfs_autobackup
    cli()
  File "/mnt/ssdpool/scriptroot/scripts/autobackup/venv/lib/python3.11/site-packages/zfs_autobackup/ZfsAutobackup.py", line 546, in cli
    failed_datasets=ZfsAutobackup(sys.argv[1:], False).run()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/ssdpool/scriptroot/scripts/autobackup/venv/lib/python3.11/site-packages/zfs_autobackup/ZfsAutobackup.py", line 532, in run
    self.error("Exception: " + str(e))
  File "/mnt/ssdpool/scriptroot/scripts/autobackup/venv/lib/python3.11/site-packages/zfs_autobackup/CliBase.py", line 98, in error
    self.log.error(txt)
  File "/mnt/ssdpool/scriptroot/scripts/autobackup/venv/lib/python3.11/site-packages/zfs_autobackup/LogConsole.py", line 33, in error
    print("! " + txt, file=sys.stderr)
OSError: [Errno 5] Input/output error

**Comment by ghan1t** [comment]
- Does the backup always fail during the same third dataset? Or is it a timeout thing?
- Does zfs-autobackup log anything more with the --debug-output options? I see you put -d -v in the config but I don't see any output in the logs. You could compare that output from this script and when you run it zfs-autobackup directly.

**Comment by wolmeh** [comment]
> * Does the backup always fail during the same third dataset? Or is it a timeout thing?

It fails after the first subdataset with a larger amount of data, about 600 GB. The error is shown before completion of send/recv of the subdataset, so about a couple of minutes after the backup script have started. I do not think it's something like a timeout. Probably it depends on the number of datasets to backup or the amount of data?

**Comment by wolmeh** [comment]
> * Does zfs-autobackup log anything more with the --debug-output options? I see you put -d -v in the config but I don't see any output in the logs. You could compare that output from this script and when you run it zfs-autobackup directly.

There are no more log entries. When I run zfs-autobackup directly without your trigger script the error does not occur.

**Comment by wolmeh** [comment]
Today I made two incremental backup of my main dataset with 10 subdatasets, just about 3 GB. No errors. Probably the error on initial run - about 3 TB - has indeed something to do with a timeout?

**Comment by ghan1t** [comment]
@wolmeh I have pushed a change that might fix this. Do you have a possibility to test this again?
ChatGPT pointed out that the error comes from zfs-autobackup writing to std:err
```
File "/mnt/ssdpool/scriptroot/scripts/autobackup/venv/lib/python3.11/site-packages/zfs_autobackup/LogConsole.py", line 33, in error
print("! " + txt, file=sys.stderr)
OSError: [Errno 5] Input/output error
```
and recommended to capture the output instead of letting it accumulate. I had indeed only captured std:out and not std:err, which I now changed.

I'll close this ticket as I'm otherwise unable to reproduce it.
